----- CREATE SEQUENCES ----

CREATE SEQUENCE customer_seq
  START WITH 1
  INCREMENT BY 1
  CACHE 100;

CREATE SEQUENCE supplier_seq
  START WITH 1
  INCREMENT BY 1
  CACHE 100;

CREATE SEQUENCE warehouse_seq
  START WITH 1
  INCREMENT BY 1
  CACHE 100;

CREATE SEQUENCE pay_method_seq
  START WITH 1
  INCREMENT BY 1
  CACHE 100;

CREATE SEQUENCE product_seq
  START WITH 1
  INCREMENT BY 1
  CACHE 100;

CREATE SEQUENCE product_cat_seq
  START WITH 1
  INCREMENT BY 1
  CACHE 100;

CREATE SEQUENCE invoice_seq
  START WITH 1
  INCREMENT BY 1
  CACHE 100;

CREATE SEQUENCE orders_seq
  START WITH 1
  INCREMENT BY 1
  CACHE 100;

CREATE SEQUENCE returns_seq
  START WITH 1
  INCREMENT BY 1
  CACHE 100;