--WAREHOUSE DATA
EXECUTE DATA_INSERTION.INSERT_WAREHOUSE('WASHINGTON STREET','NEWTON','MA',02344,0);
EXECUTE DATA_INSERTION.INSERT_WAREHOUSE('PARKER STREET','QUINCY','MA',02533,0);
EXECUTE DATA_INSERTION.INSERT_WAREHOUSE('EDISON STREET','CONCORD','MA',02543,0);

-- Invalid City Error
EXECUTE DATA_INSERTION.INSERT_WAREHOUSE('EDISON STREET','Worcester','MA',02543,0);
/

--PRODUCT CATEGORY DATA--
EXECUTE DATA_INSERTION.INSERT_PRODUCT_CATEGORY('ELECTRONICS','Iphones, Laptops and Tablets'); 
EXECUTE DATA_INSERTION.INSERT_PRODUCT_CATEGORY('SKINCARE','Creams, Gels and Serums'); 
EXECUTE DATA_INSERTION.INSERT_PRODUCT_CATEGORY('STATIONERY','Pens, Books and Backpacks'); 
EXECUTE DATA_INSERTION.INSERT_PRODUCT_CATEGORY('SPORTSWEAR','Bottoms, Shoes and Belts'); 

--- Invalid Category
EXECUTE DATA_INSERTION.INSERT_PRODUCT_CATEGORY('Automobile','Cars, Bus and Bikes'); 
--- Very long Description
EXECUTE DATA_INSERTION.INSERT_PRODUCT_CATEGORY('Automobile','Cars, Bus and Bikes, Electronic Vehicles, Electical Charging Stations'); 

/
--PAYMENT_METHOD DATA--
EXECUTE DATA_INSERTION.INSERT_PAYMENT_METHOD('CASH'); 
EXECUTE DATA_INSERTION.INSERT_PAYMENT_METHOD('CARD'); 
EXECUTE DATA_INSERTION.INSERT_PAYMENT_METHOD('NETBANKING');

-- Invalid Payment Method
EXECUTE DATA_INSERTION.INSERT_PAYMENT_METHOD('Apple Pay');

/

COMMIT;
/
SELECT * FROM WAREHOUSE;
select * from product_category;
SELECT * FROM PAYMENT_METHOD;