CREATE INDEX CUSTOMER_Username ON CUSTOMER(USERNAME);

CREATE INDEX PRODUCT_NAMEIDX ON PRODUCT(PRODUCT_NAME);

CREATE INDEX CUSTOMER_NAME ON CUSTOMER(FIRSTNAME, LASTNAME);

CREATE INDEX SUPPLIER_NAME ON SUPPLIER(SUPPLIER_NAME);